### ISSUE TITLE
Right/Left.csv not found

### ISSUE THREAD

**Issue by gaboss222** [Bizcast/NoitomHi5CalibrationByNotUsingHmd#15]
When I perform a calibration using VIVE Tracker, I obtain (in AppData/Roaming/HI5) 2 files :
CalibrationData (just a file without extension)
OpticalDeviceBindInfo.XML (With name/version, information about hi5 gloves)

Now, what am I supposed to do with these 2 files to get the LEFT/RIGHT.csv?

**Comment by gaboss222** [comment]
@Bizcast

**Comment by karukaru808** [comment]
This binary create "OpticalData" folder in AppData/Roaming/HI5 when is started.
If "OpticalData" folder don't create, CSV file don't create.
Please create "OpticalData" folder or restarted binary.

This behavior will fix.
